### PR TITLE
Updated Squid demo for PyQt5. Fixes axis of plot of HH-parameters

### PR DESCRIPTION
**Pull request by subhacom**
The existing version of Squid Demo was written for PyQt4. Now PyQt4 is obsolete, so this was updated to use PyQt5. There have also been some changes in matplotlib API and the code has been updated to handle those.

### CODE REVIEW

**Comment by subhacom** [comment]
@dilawar @hrani can you please take a look at this? There are a bunch of older pull requests stuck at 
"continuous-integration/travis-ci Expected — Waiting for status to be reported "

**Comment by dilawar** [comment]
I have given up on moose @subhacom . Some of my PR are still waiting response after 4 years. Not a great feeling! 

best,
    Dilawar

**Review by upibhalla — APPROVED** [review]
OK

**Comment by subhacom** [comment]
All pull requests on the moose-examples repo seem to get stuck at some Travis-CI check despite being approved.

"Some checks haven’t completed yet
1 expected check
continuous-integration/travis-ci Expected — Waiting for status to be reported "

@upibhalla @hrani Can you please take a look? When I try to use Travis it tells me that the number of users for this repo is limited. So probably the repo owner should modify the checks. StackOverflow question related to this: https://stackoverflow.com/questions/35112185/travis-ci-waiting-for-status-to-be-reported

**Comment by subhacom** [comment]
Further updates replacing PyQt4 with PyQt5

**Comment by subhacom** [comment]
@hrani can you please look at this. Some old checks with travis-ci seem to block the merge.

**Pull request merged**
