### PR TITLE
modified some of the snippets files for documentation

### PR DESCRIPTION
**Pull request by malav4994**
changed mainly places of documentation in files with adding main() function, and changed places of variable into functions.

### CODE REVIEW

**Comment by dilawar** [comment]
@hrani  Review this PR.

**Comment by hrani** [comment]
Pull request was sent only after reviewed,
looks fine as of now

**Comment by dilawar** [comment]
@malav4994 You need to resolve the conflicts.

**Comment by dilawar** [comment]
Ping @malav4994

**Comment by dilawar** [comment]
@malav4994  This PR has been merged after travis built it fine. If something is known to break, do refer to this PR in issues. 

This PR is not merged with chamcham branch. Only with master branch.

**Pull request merged**
